### ISSUE TITLE
Tests fail in test_cmdline.Test_Cmdline

### ISSUE THREAD

**Issue by csperkins** [glasgow-ipl/ips-protodesc-code#17]
The unit tests in `test_cmdline.py` fail for me:

```
======================================================================
FAIL: test_dload_multiple_drafts (test_cmdline.Test_Cmdline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/csp/Projects/EPSRC-BrightIDEAS/repos/ips-protodesc-code/tests/test_cmdline.py", line 268, in test_dload_multiple_drafts
    self.assertEqual( f.infile.parent, rootdir / "draft" / '-'.join( (f.infile.stem.split(sep='-')[:-1])) / f.infile.stem.split(sep='-')[-1])
AssertionError: PosixPath('/private/var/folders/6j/2bkpnd_j7r905fcb15[73 chars]/06') != PosixPath('/var/folders/6j/2bkpnd_j7r905fcb15zr_7qw00[65 chars]/06')

======================================================================
FAIL: test_dload_specific_draft (test_cmdline.Test_Cmdline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/csp/Projects/EPSRC-BrightIDEAS/repos/ips-protodesc-code/tests/test_cmdline.py", line 251, in test_dload_specific_draft
    self.assertEqual( opts.infiles[0].infile.parent, rootdir / "draft" / "draft-mcquistin-augmented-ascii-diagrams" / "06")
AssertionError: PosixPath('/private/var/folders/6j/2bkpnd_j7r905fcb15[73 chars]/06') != PosixPath('/var/folders/6j/2bkpnd_j7r905fcb15zr_7qw00[65 chars]/06')

======================================================================
FAIL: test_mutliple_local_files (test_cmdline.Test_Cmdline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/csp/Projects/EPSRC-BrightIDEAS/repos/ips-protodesc-code/tests/test_cmdline.py", line 319, in test_mutliple_local_files
    self.assertEqual( outdir , _file.gen_filepath_out(opts.root_dir, _fmt ))
AssertionError: PosixPath('/var/folders/6j/2bkpnd_j7r905fcb15zr_7qw00[76 chars]ple') != PosixPath('/private/var/folders/6j/2bkpnd_j7r905fcb15[84 chars]ple')

----------------------------------------------------------------------
```

On macOS /var is a symlink to /private/var, so these are actually pointing to the same file, but something is not right with the assertion.

Suggestion: create a temporary directory in the current directory, rather than let the system decide where to put it?

**Comment by djichthys** [comment]
Issue resolved in [a3effc0](https://github.com/glasgow-ipl/ips-protodesc-code/commit/a3effc06a9de61ed1402f29a9396f3aaf10afefe)
